_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 4
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 4
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.5
            "6": 4.32.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
arch:
    value: resnet18
augment:
    value: true
batch_size:
    value: 8
epochs:
    value: 10
framework:
    value: fastai
img_size:
    value:
        - 180
        - 320
log_preds:
    value: true
lr:
    value: 0.002
pretrained:
    value: true
seed:
    value: 42
