_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 4
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 4
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.1
            "6": 4.32.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
